pygraz_website/ext/__init__.py
from .auth import Auth
from .pm import Postmark

pygraz_website/views/account.py
# -*- encoding: utf-8 -*-
"""
Basic account handling. Most of the openid methods are adapted from the
Flask-OpenID documentation.
"""
from flask import Blueprint, session, redirect, render_template, request,\
        flash, g, url_for
import pygraz_website as site
import uuid
import hashlib

from pygraz_website import forms, decorators, models, db, signals, email


module = Blueprint('account', __name__)


@module.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        form = forms.RegisterForm.from_flat(request.form)
        if form.validate():
            data = dict(form.flatten())
            openid = models.OpenID(id=session['openid'])
            db.session.add(openid)
            user = models.User()
            user.username = data['username'].lstrip().rstrip()
            user.email = data['email'].lstrip().rstrip()
            user.openids.append(openid)
            db.session.add(user)
            db.session.commit()
            return redirect(site.oid.get_next_url())
    else:
        default = {}
        for k, v in request.args.items():
            if k == 'name':
                default['username'] = v
            else:
                default[k] = v
        form = forms.RegisterForm.from_flat(default)
    return render_template('account/register.html',
            form=form, next=site.oid.get_next_url())


@module.route('/account/login', methods=['GET', 'POST'])
@site.oid.loginhandler
def login():
    if request.method == 'POST':
        form = forms.LoginForm.from_flat(request.form)
        if form.validate():
            return site.oid.try_login(form['openid'].u,
                    ask_for=['fullname', 'email'])
    else:
        form = forms.LoginForm()
    return render_template('account/login.html',
            form=form, next=request.args.get('next', '/'))


@site.oid.after_login
def login_or_register(response):
    session['openid'] = response.identity_url
    user = db.session.query(models.User).join(models.OpenID)\
            .filter(models.OpenID.id == session['openid']).first()
    if user is None:
        return redirect(url_for('.register',
                name=response.fullname,
                email=response.email, next=site.oid.get_next_url()))
    else:
        g.user = user
        return redirect(site.oid.get_next_url())


@module.route('/logout')
def logout():
    del session['openid']
    return redirect(request.args.get('next', '/'))


@module.route('/profile', methods=['GET', 'POST'])
@decorators.login_required
def edit_profile():
    # Fake the email status for now
    if request.method == 'POST':
        form = forms.EditProfileForm.from_flat(request.form)
        if form.validate():
            old_email = g.user.email
            g.user.username = form['username'].u
            g.user.email = form['email'].u
            g.user.email_notify_new_meetup = form['email_notify_new_meetup'].value
            g.user.email_notify_new_sessionidea = form['email_notify_new_sessionidea'].value
            if old_email != g.user.email:
                g.user.email_status = 'not_verified'
            db.session.add(g.user)
            db.session.commit()
            flash("Benutzerdaten gespeichert")
            return redirect(url_for('.edit_profile'))
    else:
        form = forms.EditProfileForm.from_object(g.user)
    return render_template('account/edit_profile.html', form=form)


@module.route('/email-activation/start', methods=['GET'])
@decorators.login_required
def start_email_activation():
    """
    Sends out an activation email to the address currently associated
    with the user and sets the current email as inactive.
    """
    if g.user.email_status == 'active':
        flash("Ihre E-Mail-Adresse wurde bereits aktiviert")
        return redirect(url_for('.edit_profile'))
    code = _generate_activation_code(g.user)
    activation_url = request.url_root.rstrip('/') + url_for('.activate_email', code=code)
    g.user.email_activation_code = code
    db.session.add(g.user)
    db.session.commit()
    email.send_email(g.user.email, "Aktivieren Sie Ihre E-Mail-Adresse",
        'account/emails/activation', {'user': g.user,
            'url': activation_url})
    flash(u"Es wurde eine Aktivierungsemail an {} versandt".format(g.user.email))
    return redirect(url_for('.edit_profile'))


@module.route('/email-activation/finalize')
@decorators.login_required
def activate_email():
    code = request.args.get('code', None)
    if code is not None:
        if code == g.user.email_activation_code:
            g.user.email_status = 'active'
            g.user.email_activation_code = None
            db.session.add(g.user)
            db.session.commit()
            flash("Ihre E-Mail-Adresse wurde aktiviert")
            return redirect(url_for('.edit_profile'))
        flash(u"Der von Ihnen angegebene Code ist leider ungültig")
    return render_template('account/email_activation_finalize.html')


def handle_meetup_created(meetup):
    """
    Is called when a new meetup is created and notifies all users that requested such
    a notification.
    """
    users = db.session.query(models.User)\
            .filter_by(email_status='active')\
            .filter_by(email_notify_new_meetup=True)
    if hasattr(g, "user"):
        users = users.filter(models.User.id != g.user.id)
    emails = [user.email for user in users]
    email.send_mass_email(emails, 'Neues Stammtisch', 'emails/new-meetup', ctx=dict(meetup=meetup))


def handle_sessionidea_created(sessionidea):
    users = db.session.query(models.User)\
            .filter_by(email_status='active')\
            .filter_by(email_notify_new_sessionidea=True)
    if hasattr(g, "user"):
        users = users.filter(models.User.id != g.user.id)
    emails = [user.email for user in users]
    url = '{}{}#idea-{}'.format(request.url_root.rstrip('/'), sessionidea.meetup.get_absolute_url(), sessionidea.id)
    email.send_mass_email(emails, 'Neue Sessionidea', 'emails/new-sessionidea',
            ctx=dict(idea=sessionidea, url=url))


signals.meetup_created.connect(handle_meetup_created)
signals.sessionidea_created.connect(handle_sessionidea_created)


def _generate_activation_code(user):
    raw = "{}.{}.{}".format(user.id, user.email, str(uuid.uuid4()))
    return hashlib.sha1(raw).hexdigest()[:5]

pygraz_website/views/admin.py
from collections import defaultdict
from flask import Blueprint, render_template, g

from pygraz_website import models


module = Blueprint('admin', __name__)


@module.route('/')
def index():
    return render_template('admin/index.html')


@module.route('/locks')
def locks():
    locks = defaultdict(dict)
    keys = g.redis.keys("locks:*")
    holders = {}
    if not keys:
        values = []
    else:
        values = g.redis.mget(keys)
    for l, v in zip(keys, values):
        _, type_, docid, field = l.split(":")
        locks[type_ + docid][field] = v
        if field == 'holder':
            holders[int(v)] = {}
    if holders:
        for user in models.User.query.filter(
                models.User.id.in_(map(int, holders.keys()))):
            holders[user.id] = user
    for k, v in locks.iteritems():
        v['holder'] = holders[int(v['holder'])]
    return render_template('admin/locks.html', locks=locks)

pygraz_website/views/meetups.py
# -*- encoding: utf-8 -*-
from flask import Blueprint, render_template, request, redirect, url_for,\
        current_app, g, flash, abort
from flaskext.babel import gettext as _
import datetime
import collections
from sqlalchemy.orm import joinedload

from pygraz_website import forms, decorators, utils, filters, db, models, signals


module = Blueprint('meetups', __name__)


def _extract_date(date):
    """
    Converts the date passed in via URL into a native and localized
    datetime object.

    :param date: date string in %Y-%m-%d
    :type date: string
    :returns: native date object
    """
    return datetime.datetime.strptime(date, "%Y-%m-%d")\
            .replace(tzinfo=current_app.config['local_timezone'])


def _get_meetup(date):
    """
    Returns the meetup with the given date. If no matching meetup could be
    found this raises a 404 error page.

    :param date: date string in %Y-%m%-d
    :type date: string
    """
    real_date = _extract_date(date)
    meetup = models.Meetup.query_by_date(real_date).first()
    if meetup is None:
        abort(404)
    return meetup


def _get_idea(id_, meetup):
    """
    Fetches the idea with the given idea associated with the given meetup. If
    the idea can't be found a 404 error page is raised.

    :param id_: id of an idea
    :param meetup: meetup object
    :returns: idea object
    """
    idea = db.session.query(models.Sessionidea)\
            .filter(models.Sessionidea.id == id_)\
            .filter(models.Sessionidea.meetup == meetup).first()
    if idea is None:
        abort(404)
    return idea


def do_vote(date, id, value):
    """
    Executes a voting for an idea with the given id associated with a meetup
    taking place on the given date (string). The value indicates whether the
    voting is positive or negative.

    :param date: date of a meetup. See `_get_meetup` for details
    :param id: id of an idea associated with the meetup
    :param value: 1 or -1 for voting the idea up or down
    :returns: Response initiating a redirect to the meetup
    """
    meetup = _get_meetup(date)
    idea = _get_idea(id, meetup)
    voted_users = [vote.user for vote in idea.votes.all()]
    if g.user not in voted_users:
        vote = models.SessionideaVote()
        vote.user = g.user
        vote.sessionidea_id = idea.id
        vote.value = value
    else:
        vote = db.session.query(models.SessionideaVote)\
                .filter(models.SessionideaVote.user == g.user)\
                .filter(models.SessionideaVote.sessionIdea == idea).first()
        vote.value = value
    db.session.add(vote)
    db.session.commit()
    flash(_(u"Thank you for your vote!"))
    signals.sessionidea_voted.send(vote)
    return redirect(url_for('.meetup', date=filters.datecode(meetup.start)))


@module.route('/')
def meetups():
    """
    List all meetups in chronological order
    """
    return render_template('meetups.html',
            meetups=db.session.query(models.Meetup)\
                    .filter(models.Meetup.end > datetime.datetime.utcnow()))


@module.route('/<date>')
def meetup(date):
    """
    Displays the meetup taking place on the given date.
    """
    meetup = _get_meetup(date)
    user_upvotes = []
    user_downvotes = []
    ideas = meetup.sessionideas
    idea_ids = [idea.id for idea in ideas]
    vote_results = collections.defaultdict(int)
    for vote in db.session.query(models.SessionideaVote)\
            .filter(models.SessionideaVote.sessionidea_id.in_(idea_ids)):
        vote_results[vote.sessionidea_id] += vote.value
    if g.user:
        for vote in db.session.query(models.SessionideaVote)\
                .options(joinedload('sessionIdea'))\
                .filter(models.SessionideaVote.user == g.user)\
                .filter(models.SessionideaVote.sessionidea_id.in_(idea_ids)):
            if vote.value > 0:
                user_upvotes.append(vote.sessionIdea.id)
            else:
                user_downvotes.append(vote.sessionIdea.id)
    return render_template('meetup.html',
            meetup=meetup, ideas=ideas,
            vote_results=vote_results,
            user_upvotes=user_upvotes,
            user_downvotes=user_downvotes)


@module.route('/<date>/sessionideas/add', methods=['GET', 'POST'])
@decorators.login_required
def add_sessionidea(date):
    """
    Form handling for adding a new session idea to the meetup
    taking place on the passed date.
    """
    meetup = _get_meetup(date)
    now = datetime.datetime.utcnow()
    if now > meetup.start:
        flash(_('Session ideas can only be added to future meetups'))
        return redirect(url_for('.meetup', date=date))
    if request.method == 'POST':
        form = forms.SessionIdeaForm.from_flat(request.form)
        if form.validate():
            idea = models.Sessionidea()
            idea.author = g.user
            idea.summary = form['summary'].value
            idea.details = form['details'].value
            idea.url = form['url'].value
            idea.meetup = meetup
            db.session.add(idea)
            db.session.commit()
            signals.sessionidea_created.send(idea)
            return redirect(url_for('.meetup',
                date=filters.datecode(meetup.start)))
    else:
        form = forms.SessionIdeaForm()
    return render_template('meetups/add_idea.html',
            meetup=meetup, form=form)


@module.route('/<date>/sessionideas/<id>/delete', methods=['GET', 'POST'])
@decorators.login_required
def delete_sessionidea(date, id):
    """
    Form handler for deleting a session idea.
    """
    meetup = _get_meetup(date)
    idea = _get_idea(id, meetup)
    if request.method == 'GET':
        return render_template('meetups/confirm_delete_idea.html',
                idea=idea, meetup=meetup)
    db.session.delete(idea)
    db.session.commit()
    signals.sessionidea_deleted.send(idea)
    return redirect(url_for('.meetup', date=filters.datecode(meetup.start)))


@module.route('/<date>/sessionideas/<id>/edit', methods=['GET', 'POST'])
@decorators.login_required
def edit_sessionidea(date, id):
    """
    Form handler for editing a session idea.
    """
    meetup = _get_meetup(date)
    idea = _get_idea(id, meetup)
    if g.user != idea.author:
        abort(404)
    if request.method == 'POST':
        form = forms.SessionIdeaForm.from_flat(request.form)
        if form.validate():
            idea.summary = form['summary'].value
            idea.details = form['details'].value
            idea.url = form['url'].value
            db.session.add(idea)
            db.session.commit()
            signals.sessionidea_changed.send(idea)
            flash(_('Your changes have been saved.'), category='success')
            return redirect(url_for('.meetup',
                date=filters.datecode(meetup.start)))
    else:
        form = forms.SessionIdeaForm.from_object(idea)
    return render_template('meetups/edit_idea.html',
            meetup=meetup, idea=idea, form=form)


@module.route('/<date>/sessionideas/<id>/up')
@decorators.login_required
def vote_up_sessionidea(date, id):
    return do_vote(date, id, 1)


@module.route('/<date>/sessionideas/<id>/down')
@decorators.login_required
def vote_down_sessionidea(date, id):
    return do_vote(date, id, -1)


@module.route('/<date>/sessionideas/<id>/unvote')
@decorators.login_required
def unvote_sessionidea(date, id):
    meetup = _get_meetup(date)
    idea = _get_idea(id, meetup)
    vote = db.session.query(models.SessionideaVote)\
            .filter(models.SessionideaVote.user == g.user)\
            .filter(models.SessionideaVote.sessionIdea == idea).first()
    if vote is not None:
        db.session.delete(vote)
        db.session.commit()
        flash(_('Vote removed'))
        signals.sessionidea_unvoted.send(vote)
    return redirect(url_for('.meetup', date=filters.datecode(meetup.start)))


@module.route('/<date>/edit', methods=['GET', 'POST'])
@decorators.admin_required
def edit_meetup(date):
    real_date = _extract_date(date)
    meetup = models.Meetup.query_by_date(real_date).first()
    print meetup.meetupcom_eventid
    with utils.DocumentLock(meetup) as lock:
        if request.method == 'POST':
            form = forms.MeetupForm.from_flat(request.form)
            if form.validate({'meetup': meetup}):
                if 'preview' not in request.form:
                    meetup.start = form['start'].value
                    meetup.end = form['end'].value
                    meetup.location = form['location'].value
                    meetup.address = form['address'].value
                    meetup.notes = form['notes'].value
                    meetup.meetupcom_eventid = form['meetupcom_eventid'].value
                    db.session.add(meetup)
                    db.session.commit()
                    lock.unlock()
                    signals.meetup_changed.send(meetup)
                    flash(_('Your changes have been saved.'))
                    return redirect(url_for('.meetup',
                        date=filters.datecode(meetup.start)))
        else:
            form = forms.MeetupForm.from_object(meetup)
        return render_template('meetups/edit.html',
                meetup=meetup,
                preview='preview' in request.form,
                form=form)


@module.route('/<date>/delete', methods=['GET', 'POST'])
@decorators.admin_required
def delete_meetup(date):
    real_date = _extract_date(date)
    meetup = models.Meetup.query_by_date(real_date).first()
    if meetup is None:
        abort(404)
    if request.method == 'POST':
        with utils.DocumentLock(meetup) as lock:
            db.session.delete(meetup)
            db.session.commit()
            lock.unlock()
            signals.meetup_deleted.send(meetup)
        return redirect(url_for('.meetups'))
    else:
        return render_template('meetups/confirm_delete_meetup.html',
                meetup=meetup)

pygraz_website/templates/base.html
<!DOCTYPE HTML>
<html>
    <head>
        <link rel="stylesheet" href="/static/s/screen.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/static/s/print.css" type="text/css" media="print" />
        <link href="https://plus.google.com/101185345132127945047" rel="publisher" />
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <!--
        <script type="text/javascript">
            $(function(){
                $('#logo').hover(function(ev){
                    var src = $('img', $(this)).attr('src');
                    $('img', $(this)).attr('src', src.replace('-mono', ''));
                }, function(ev){
                    var src = $('img', $(this)).attr('src');
                    $('img', $(this)).attr('src', src.replace('.png', '-mono.png'));
                })
            });
        </script>
        -->
        <title>{% block title %}Willkommen{% endblock %} - pyGRAZ</title>
        {% block head %}{% endblock %}
    </head>
    <body class="{% block bodyclass %}{% endblock %}">
        <div id="page">
            <header>
                <nav id="accountnav">
                    <ul>
                        {% if not g.user %}
                        <li><a href="{{ url_for('account.login') }}?next={{ request.path }}">Anmelden</a></li>
                        {% else %}
                        <li><a href="{{ url_for('account.edit_profile') }}">Meine Profil</a></li>
                        <li><a href="{{ url_for('account.logout') }}?next={{ request.path }}">Abmelden</a></li>
                        {% if is_admin %}
                        <li><a href="{{ url_for('admin.index') }}" class="{% block nav_admin %}{% endblock %}">Admin</a></li>
                        {% endif %}
                        {% endif %}
                    </ul>
                </nav>
                <a href="/" id="logo"><img src="/static/s/logo.png" alt="pyGRAZ" /></a>
                <nav id="mainnav">
                    <ul>
                        <li><a href="/" class="{% block nav_start %}{% endblock %}">Start</a></li>
                        <li><a href="{{ url_for('meetups.meetups') }}" class="{% block nav_meetups %}{% endblock %}">Treffen</a></li>
                        {#
                        <li><a href="{{ url_for('companies.index') }}" class="{% block nav_companies %}{% endblock %}">Firmen</a></li>
                        #}
                        <li><a href="http://groups.google.at/group/python-graz" class="{% block nav_about %}{% endblock %}">Mailinglist</a></li>
                        <li><a href="http://www.meetup.com/r/inbound/0/0/shareimg/http://www.meetup.com/PyGRAZ/?a=shareimg"><img border="0" alt="Python User Group Graz" src="http://img.meetup.com/img/logo_45.png"></a></li>
                        <li><a href="https://plus.google.com/101185345132127945047?prsrc=3" style="text-decoration: none;"><img src="/static/s/gplus-32.png" alt="Google+" width="32" height="32" style="border: 0;"/></a></li>
                    </ul>
                </nav>
            </header>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <ul id="flashes">
                    {% for category, message in messages %}
                        <li class="{{ category }}">{{ message }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
            <div id="main">
                {% block main %}
                <div id="body"><div class="wrapper">
                    {% block body %}{% endblock %}
                </div></div>
                <div id="sidebar">
                    {% block sidebar %}{% endblock %}
                </div>
                {% endblock %}
            </div>
            <footer>
                {% block footer %}{% endblock %}
                <p id="credits">Meetup.com logo provided by <a href="http://www.meetup.com/">meetup.com</a>.</p>
            </footer>
        </div>
    </body>
</html>

pygraz_website/templates/confirm_base.html
{% extends "base.html" %}
{% block body %}
<form method="post" class="confirm">
    {% block question %}{% endblock %}
    <button type="submit">Ja</button>
    <a href="/">Abbrechen</a>
</form>
{% endblock %}

pygraz_website/templates/confirm_purge.html
{% extends "base.html" %}
{% block body %}
<form method="post" class="confirm">
    <p>Bist du sicher, dass du diese Version endgültig löschen möchtest?</p>
    <button type="submit">Ja</button>
    <a href="/">Abbrechen</a>
</form>
{% endblock %}

pygraz_website/templates/index.html
{% extends "base.html" %}
{% block nav_start %}active{% endblock %}
{% block bodyclass %}frontpage{% endblock %}
{% import "helpers/base.html" as base with context %}
{% block head %}
<link rel="stylesheet" href="/static/s/frontpage.css" type="text/css" media="screen" />
{% endblock %}
{% block main %}
<div id="teaser">
    <div id="teaser-w">
        <div id="info" class="content">
            <h1>Die Grazer Python-Usergroup</h1>
            <p>Python-Programmierer oder interessiert? Die Python-Usergroup-Graz ist
            ein loser Haufen (sprich: Keine fixe Mitgliedschaft) Gleichgesinnter,
            der sich einmal im Monat trifft, um Neuigkeiten auszutauschen und Wissen
            zu vermitteln.</p>
            <p>Desweiteren möchten wir helfen, Python und die darauf aufbauenden Projekte
            in Graz bekannter zu machen und auch arbeitsuchenden Python-Programmierern
            helfen.</p>
        </div>
        <div id="quote" class="content">
        <blockquote>
            <p>Python is a general-purpose high-level programming language[2] whose 
            design philosophy emphasizes code readability.[3] Python aims to combine
            "remarkable power with very clear syntax",[4] and its standard library is
            large and comprehensive. Its use of indentation for block delimiters is 
            unusual among popular programming languages.</p>
            <cite>-- <a href="http://en.wikipedia.org/wiki/Python_(programming_language)">wikipedia.org</a></cite>
        </blockquote>
        </div>
    </div>
</div>
<div id="misc">
    <div id="next-meetup">
        <h2>Nächstes Treffen</h2>
        {% if next_meetup %}
        <p><a href="{{ url_for('meetups.meetup', date=next_meetup.start|datecode)}}">{{ next_meetup.start|date }}</a>,
        {{ next_meetup.start|time }} - {{ next_meetup.end|time }}
        {% if next_meetup.location %}
            {% if next_meetup.location == 'Google+' %}
                {{ base.location_info(next_meetup.location) }}
            {% else %}
                <br />{{ next_meetup.location }}
                {% if next_meetup.address %}
                , {{ next_meetup.address }}
                {% endif %}
            {% endif %}
        {% endif %}
        </p>
        {% if next_meetup and next_meetup.address %}
            <iframe id="map" width="423" height="350" frameborder="0" scrolling="no" 
                marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q={{ next_meetup.address|urlencode }}&amp;output=embed"></iframe>
        {% endif %}
        {% else %}
        <p>Derzeit ist kein Treffen geplant. In der Regel findet aber so etwas einmal im Monat statt, weshalb sich
        dieser leere Fleck sicher bald füllen sollte :-)</p>
        {% endif %}
    </div>
    <div id="news">
        <h2>Neuigkeiten</h2>
        <ul>
            {% for item in news %}
            <li>
            <p class="content">{{ item.text|e|urlize|safe }}</p>
            <a href="{{ item.url }}" class="date">{{ item.utc_created_at|date }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}
{% block sidebar %}
{% endblock %}

pygraz_website/templates/meetup.html
{% extends "meetups/base.html" %}
{% import "helpers/base.html" as base with context %}
{% block title %}Treffen vom {{ meetup.start|date }}{% endblock %}
{% block body %}
    <h1>Treffen vom {{ meetup.start|date }}</h1>
    {% if meetup.meetupcom_eventid and meetup|in_future %}
    <div class="meetupcom">
        <p>
            Falls du kommen möchtest, melde dich bitte bei Gelegenheit auf <a href="http://www.meetup.com/PyGRAZ/events/{{ meetup.meetupcom_eventid }}/">Meetup.com</a>
            zu diesem Treffen an.
        </p>
        <p class="info">
            Eine Anmeldung ist zwar nicht zwingend erforderlich, hilft uns aber bei der Organisation.
        </p>
    </div>
    {% endif %}
    {% if meetup.notes %}
    {{ meetup.notes|rst|safe }}
    {% else %}
    <p>Keine Notizen vorhanden.</p>
    {% endif %}
    {% if is_admin %}
        <a href="{{ url_for('.edit_meetup', date=meetup.start|datecode) }}" class="edit">Treffen ändern</a>
        <a href="{{ url_for('.delete_meetup', date=meetup.start|datecode) }}" class="edit">Treffen löschen</a>
    {% endif %}
    <section id="ideas">
        <h1>Themenvorschläge</h1>
        {% if ideas %}
        <ul>
            {% for idea in ideas %}
            <li id="idea-{{ idea.id }}"><h2 class="summary">
                    {% if idea.url %}
                    <a href="{{ idea.url }}" rel="nofollow">{{ idea.summary }}</a>
                    {% else %}
                    {{ idea.summary }}
                    {% endif %} ({{ vote_results[idea.id] }})
                </h2>
                {% if idea.details %}
                <div class="details">{{ idea.details|rst|safe }}</div>
                {% endif %}
                <p class="actions">
                {% if is_logged_in %}
                    {% if idea.id in user_upvotes %}
                    <a href="{{ url_for('meetups.unvote_sessionidea', date=meetup.start|datecode, id=idea.id) }}" class="upvote unvote">+1</a>
                    {% else %}
                    <a href="{{ url_for('meetups.vote_up_sessionidea', date=meetup.start|datecode, id=idea.id) }}" class="upvote">+1</a>
                    {% endif %}


                    {% if idea.id in user_downvotes %}
                    <a href="{{ url_for('meetups.unvote_sessionidea', date=meetup.start|datecode, id=idea.id) }}" class="downvote unvote">-1</a>
                    {% else %}
                    <a href="{{ url_for('meetups.vote_down_sessionidea', date=meetup.start|datecode, id=idea.id) }}" class="downvote">-1</a>
                    {% endif %}
                {% endif %}
                {% if idea.user == g.user or is_admin %}
                <a href="{{ url_for('meetups.edit_sessionidea', date=meetup.start|datecode, id=idea.id) }}">Editieren</a>
                <a href="{{ url_for('meetups.delete_sessionidea', date=meetup.start|datecode, id=idea.id) }}">Löschen</a>
                {% endif %}
                </p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>Es hat leider noch keine Themenvorschläge für dieses Meetup eingetragen.</p>
        {% endif %}
    {% if is_logged_in %}
    <a class="add-idea" href="{{ url_for('meetups.meetup', date=meetup.start|datecode) }}/sessionideas/add">Neuen Themenvorschlag hinzufügen</a>
    {% endif %}
{% endblock %}
{% block sidebar %}
{{ super() }}
<div class="block" id="info">
    <div class="content">
        {% if meetup.location and meetup.address %}
        <iframe id="map" width="270" height="200" frameborder="0" scrolling="no" 
            marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q={{ meetup.address|urlencode }}&amp;output=embed&amp;iwloc="></iframe>
        {% endif %}
        {% if meetup.start %}
        <dl>
            <dt>Beginn:</dt>
            <dd>{{ meetup.start|datetime }}</dd>
        </dl>
        {% endif %}
        {% if meetup.end %}
        <dl>
            <dt>Geplantes Ende:</dt>
            <dd>{{ meetup.end|datetime }}</dd>
        </dl>
        {% endif %}
        {% if meetup.location %}
        <dl>
            <dt>Ort:</dt>
            <dd>{{ meetup.location }}</dd>
        </dl>
        {% if meetup.address %}
        <dl>
            <dt>Adresse:</dt>
            <dd>{{ meetup.address }}</dd>
        </dl>
        {% endif %}
        {{ base.location_info(meetup.location) }}
        {% endif %}
    </div>
</div>
{% include "_docinfo.html" %}
{% endblock %}
{% block subnav_archive %}active{% endblock %}